[env:heltec_wifi_lora_32_V3]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino

; Serial Monitor Configuration
monitor_speed = 115200

monitor_dtr = 1
monitor_rts = 1

; Mandatory flags for ESP32-S3 (Heltec V3)
; Ensures the native USB-C port works correctly for the Serial Monitor
build_flags = 
    -D ARDUINO_USB_MODE=1  ; Sets USB mode to CDC (Serial Communication)
    -D ARDUINO_USB_CDC_ON_BOOT=1  ; This forces USB to turn on at boot
    

; Flash Memory Configuration (Sets LittleFS instead of legacy SPIFFS)
board_build.filesystem = littlefs

; Dependency Manager (Libraries PlatformIO will download automatically)
lib_deps = 
    knolleary/PubSubClient@ ^2.8.0        ; Classic and robust MQTT client
    bblanchon/ArduinoJson@ ^7.0.4         ; To format data as JSON before sending
    adafruit/Adafruit SSD1306@ ^2.5.9     ; For the OLED display
    adafruit/Adafruit GFX Library@ ^1.11.9 ; Graphics library required for the SSD1306